---
to: ./k8s/monitoring/configs/<%=app_name%>-monitor.yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/component: monitoring
  name: <%=app_name%>-monitor
  namespace: monitoring
spec:
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - <%=app_name%>-ns
  selector:
    matchLabels:
      app: <%=app_name%>
