---
to: cluster/apps.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-ingresses
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-addons
  interval: 1m0s
  retryInterval: 1m0s
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/apps/ingresses
  prune: true
  wait: true
