{
 "title": "<%=app_name%> ActiveJob",
 "description": "Example dashboard for metrics provided by yabeda-activejob gem for monitoring rails activejobs.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Failed Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(activejob) (activejob_failed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(activejob) (activejob_success_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs processed every second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(activejob_success_total[1m]))",
     "legendFormat": "Successful jobs"
    },
    {
     "expr": "sum(rate(activejob_failed_total[1m]))",
     "legendFormat": "Failed jobs"
    },
    {
     "expr": "sum(rate(activejob_executed_total[1m]))",
     "legendFormat": "Executed jobs"
    }
   ]
  },
  {
   "title": "Jobs processed by queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(activejob_executed_total[5m])) by (queue)",
     "legendFormat": "Executed in {{queue}}"
    }
   ]
  },
  {
   "title": "Jobs processed by class",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(activejob_success_total[1m])) by (activejob)",
     "legendFormat": "{{activejob}}"
    }
   ]
  },
  {
   "title": "Job latency",
   "type": "timeseries",
   "description": "Job latency is the difference in seconds since the oldest job in the queue was enqueued. Or how long job is waiting its turn to be executed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(activejob_latency_seconds_bucket[1m])) by (activejob, le)) ",
     "legendFormat": "{{activejob}}"
    }
   ]
  },
  {
   "title": "Queue latency",
   "type": "timeseries",
   "description": "Queue latency is the difference in seconds since the oldest job in the queue was enqueued. Or how long job is waiting its turn to be executed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(activejob_latency_seconds_bucket[1m])) by (queue, le)) ",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Job processing average time by class",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(activejob_runtime_seconds_bucket[1m])) by (activejob, le)) ",
     "legendFormat": "{{activejob}}"
    }
   ]
  },
  {
   "title": "Job processing average time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(activejob_runtime_seconds_bucket[1m])) by (le)) ",
     "legendFormat": "95% quantile of activejob "
    }
   ]
  },
  {
   "title": "ActiveJobs pushed by queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(activejob_enqueued_total[1m])) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  }
 ]
}