{
 "title": "<%=app_name%> Rails",
 "description": "Basic metrics for web applications built with Ruby on Rails.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(rails_requests_total{namespace=\"<%=app_name%>-ns\"}[10m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Rails average response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(rails_request_duration_seconds_sum{namespace=\"<%=app_name%>-ns\"}[10m])) > 0) / sum(rate(rails_request_duration_seconds_count{namespace=\"<%=app_name%>-ns\"}[10m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "(sum(rate(rails_db_runtime_seconds_sum{namespace=\"<%=app_name%>-ns\"}[10m])) > 0) / sum(rate(rails_db_runtime_seconds_count{namespace=\"<%=app_name%>-ns\"}[10m]))",
     "legendFormat": "ActiveRecord"
    },
    {
     "expr": "(sum(rate(rails_view_runtime_seconds_sum{namespace=\"<%=app_name%>-ns\"}[10m])) > 0) / sum(rate(rails_view_runtime_seconds_count{namespace=\"<%=app_name%>-ns\"}[10m]))",
     "legendFormat": "Views"
    }
   ]
  },
  {
   "title": "Rails 95% response time by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rails_request_duration_seconds_bucket[10m])) by (le,controller,action))",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Throughput / Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rails_requests_total[10m])) by (controller, action)",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  }
 ]
}