---
to: ./k8s/apps/base/<%=app_name%>-<%=rails_env%>/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: <%=app_name%>-<%=rails_env%>-service
  namespace: <%=app_name%>-<%=rails_env%>-ns
  annotations:
    external-dns.alpha.kubernetes.io/hostname: <%=sub_domain%>.<%=public_domain%>
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <%=ssl_cert_arn%>
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "https"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 3000
      protocol: TCP
      name: web
  selector:
    app: <%=app_name%>-<%=rails_env%>
