---
to: k8s/infrastructure/addons/cluster-autoscaler.yaml
---
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cluster-autoscaler
      version: 9.34.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    serviceMonitor:
      enabled: true
      interval: "10s" # Scrape interval
      namespace: monitoring
      path: /metrics
      port: http
      selector:
        release: kube-prometheus-stack
    autoDiscovery:
      clusterName: <%=platfrom_name%>-cluster
    awsRegion: us-east-1
    cloudProvider: aws
    rbac:
      serviceAccount:
        create: false
        name: sa-cluster-autoscaler
    replicaCount: 2
  interval: 10m0s
  releaseName: cluster-autoscaler
  targetNamespace: kube-system